services:
    app:
        build:
            args:
                USER: $CONTAINER_APP_USER
                GROUP: $CONTAINER_APP_GROUP
                ID: $CONTAINER_APP_ID
            context: docker/php/8.1
            dockerfile: Dockerfile
        image: storyforumapi
        container_name: story-forum-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - forum

    db:
        image: mariadb:10.9.3
        container_name: storyforumapi-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_USER: $DB_USERNAME
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - forum

    nginx:
        image: nginx:1.23.1-alpine
        container_name: storyforumapi-nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - forum

networks:
    forum:
        driver: bridge
